In [200]:
import pandas as pd
import numpy as np
from itertools import product
pd.set_option('display.max_rows',1000)

In [259]:
ints=400
df=pd.DataFrame(np.array(range(ints)).reshape(20,20))

In [260]:
indx_dct=df.to_dict()

In [261]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
1,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39
2,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59
3,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79
4,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99
5,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119
6,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139
7,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159
8,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179
9,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199
10,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219
11,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239
12,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259
13,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279
14,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299
15,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319
16,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339
17,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359
18,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379
19,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399

In [262]:
def traversal_(r,c):
    dct={}
    bndry = df.shape
    #print bndry
    if (r >=0 and r< bndry[0]):
        dct[r]=[x for x in [c-1,c+1] if (x >=0 and x< bndry[1])]
        
    if (r-1 >=0 and r-1< bndry[0]): 
        dct[r-1]=[x for x in [c-1,c,c+1] if (x >=0 and x< bndry[1])]
    
    if (r+1 >=0 and r+1< bndry[0]):
        dct[r+1]=[x for x in [c-1,c,c+1] if (x >=0 and x< bndry[1])]
    
        
    return dct

In [263]:
# from row 3 column 2 I can go to row 2 col 1,2 or 3
# or row 3 col 1 or 3 .... 
traversal_(1,1)

{0: [0, 1, 2], 1: [0, 2], 2: [0, 1, 2]}

In [264]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
1,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39
2,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59
3,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79
4,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99
5,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119
6,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139
7,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159
8,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179
9,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199
10,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219
11,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239
12,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259
13,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279
14,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299
15,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319
16,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339
17,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359
18,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379
19,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399

In [265]:
indicies=list(product(indx_dct.keys(),indx_dct.keys()))

In [266]:
print indicies

[(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (0, 12), (0, 13), (0, 14), (0, 15), (0, 16), (0, 17), (0, 18), (0, 19), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (1, 12), (1, 13), (1, 14), (1, 15), (1, 16), (1, 17), (1, 18), (1, 19), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (2, 11), (2, 12), (2, 13), (2, 14), (2, 15), (2, 16), (2, 17), (2, 18), (2, 19), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (3, 11), (3, 12), (3, 13), (3, 14), (3, 15), (3, 16), (3, 17), (3, 18), (3, 19), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (4, 10), (4, 11), (4, 12), (4, 13), (4, 14), (4, 15), (4, 16), (4, 17), (4, 18), (4, 19), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 9), (5, 10), (5, 11), (5, 12), (5, 13), (5, 14), (5, 15), (5, 16), (5, 17), (5, 18), (5, 19), (6, 0), (6, 1), (6, 2), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (6, 8), (6, 9), (6, 10), (6, 11), (6, 12), (6, 13), (6, 14), (6, 15), (6, 16), (6, 17), (6, 18), (6, 19), (7, 0), (7, 1), (7, 2), (7, 3), (7, 4), (7, 5), (7, 6), (7, 7), (7, 8), (7, 9), (7, 10), (7, 11), (7, 12), (7, 13), (7, 14), (7, 15), (7, 16), (7, 17), (7, 18), (7, 19), (8, 0), (8, 1), (8, 2), (8, 3), (8, 4), (8, 5), (8, 6), (8, 7), (8, 8), (8, 9), (8, 10), (8, 11), (8, 12), (8, 13), (8, 14), (8, 15), (8, 16), (8, 17), (8, 18), (8, 19), (9, 0), (9, 1), (9, 2), (9, 3), (9, 4), (9, 5), (9, 6), (9, 7), (9, 8), (9, 9), (9, 10), (9, 11), (9, 12), (9, 13), (9, 14), (9, 15), (9, 16), (9, 17), (9, 18), (9, 19), (10, 0), (10, 1), (10, 2), (10, 3), (10, 4), (10, 5), (10, 6), (10, 7), (10, 8), (10, 9), (10, 10), (10, 11), (10, 12), (10, 13), (10, 14), (10, 15), (10, 16), (10, 17), (10, 18), (10, 19), (11, 0), (11, 1), (11, 2), (11, 3), (11, 4), (11, 5), (11, 6), (11, 7), (11, 8), (11, 9), (11, 10), (11, 11), (11, 12), (11, 13), (11, 14), (11, 15), (11, 16), (11, 17), (11, 18), (11, 19), (12, 0), (12, 1), (12, 2), (12, 3), (12, 4), (12, 5), (12, 6), (12, 7), (12, 8), (12, 9), (12, 10), (12, 11), (12, 12), (12, 13), (12, 14), (12, 15), (12, 16), (12, 17), (12, 18), (12, 19), (13, 0), (13, 1), (13, 2), (13, 3), (13, 4), (13, 5), (13, 6), (13, 7), (13, 8), (13, 9), (13, 10), (13, 11), (13, 12), (13, 13), (13, 14), (13, 15), (13, 16), (13, 17), (13, 18), (13, 19), (14, 0), (14, 1), (14, 2), (14, 3), (14, 4), (14, 5), (14, 6), (14, 7), (14, 8), (14, 9), (14, 10), (14, 11), (14, 12), (14, 13), (14, 14), (14, 15), (14, 16), (14, 17), (14, 18), (14, 19), (15, 0), (15, 1), (15, 2), (15, 3), (15, 4), (15, 5), (15, 6), (15, 7), (15, 8), (15, 9), (15, 10), (15, 11), (15, 12), (15, 13), (15, 14), (15, 15), (15, 16), (15, 17), (15, 18), (15, 19), (16, 0), (16, 1), (16, 2), (16, 3), (16, 4), (16, 5), (16, 6), (16, 7), (16, 8), (16, 9), (16, 10), (16, 11), (16, 12), (16, 13), (16, 14), (16, 15), (16, 16), (16, 17), (16, 18), (16, 19), (17, 0), (17, 1), (17, 2), (17, 3), (17, 4), (17, 5), (17, 6), (17, 7), (17, 8), (17, 9), (17, 10), (17, 11), (17, 12), (17, 13), (17, 14), (17, 15), (17, 16), (17, 17), (17, 18), (17, 19), (18, 0), (18, 1), (18, 2), (18, 3), (18, 4), (18, 5), (18, 6), (18, 7), (18, 8), (18, 9), (18, 10), (18, 11), (18, 12), (18, 13), (18, 14), (18, 15), (18, 16), (18, 17), (18, 18), (18, 19), (19, 0), (19, 1), (19, 2), (19, 3), (19, 4), (19, 5), (19, 6), (19, 7), (19, 8), (19, 9), (19, 10), (19, 11), (19, 12), (19, 13), (19, 14), (19, 15), (19, 16), (19, 17), (19, 18), (19, 19)]

In [267]:
Range_df=pd.DataFrame({x:traversal_(x[0],x[1]) for x in indicies}).T.fillna('')

In [268]:
#row column, row and column again
#at row 0 column 0  you can make a move to row 0 column 1 or row 1 column 0 or column 1

Range_df

                 0             1             2             3             4   \
0  0            [1]        [0, 1]
   1         [0, 2]     [0, 1, 2]
   2         [1, 3]     [1, 2, 3]
   3         [2, 4]     [2, 3, 4]
   4         [3, 5]     [3, 4, 5]
   5         [4, 6]     [4, 5, 6]
   6         [5, 7]     [5, 6, 7]
   7         [6, 8]     [6, 7, 8]
   8         [7, 9]     [7, 8, 9]
   9        [8, 10]    [8, 9, 10]
   10       [9, 11]   [9, 10, 11]
   11      [10, 12]  [10, 11, 12]
   12      [11, 13]  [11, 12, 13]
   13      [12, 14]  [12, 13, 14]
   14      [13, 15]  [13, 14, 15]
   15      [14, 16]  [14, 15, 16]
   16      [15, 17]  [15, 16, 17]
   17      [16, 18]  [16, 17, 18]
   18      [17, 19]  [17, 18, 19]
   19          [18]      [18, 19]
1  0         [0, 1]           [1]        [0, 1]
   1      [0, 1, 2]        [0, 2]     [0, 1, 2]
   2      [1, 2, 3]        [1, 3]     [1, 2, 3]
   3      [2, 3, 4]        [2, 4]     [2, 3, 4]
   4      [3, 4, 5]        [3, 5]     [3, 4, 5]
   5      [4, 5, 6]        [4, 6]     [4, 5, 6]
   6      [5, 6, 7]        [5, 7]     [5, 6, 7]
   7      [6, 7, 8]        [6, 8]     [6, 7, 8]
   8      [7, 8, 9]        [7, 9]     [7, 8, 9]
   9     [8, 9, 10]       [8, 10]    [8, 9, 10]
   10   [9, 10, 11]       [9, 11]   [9, 10, 11]
   11  [10, 11, 12]      [10, 12]  [10, 11, 12]
   12  [11, 12, 13]      [11, 13]  [11, 12, 13]
   13  [12, 13, 14]      [12, 14]  [12, 13, 14]
   14  [13, 14, 15]      [13, 15]  [13, 14, 15]
   15  [14, 15, 16]      [14, 16]  [14, 15, 16]
   16  [15, 16, 17]      [15, 17]  [15, 16, 17]
   17  [16, 17, 18]      [16, 18]  [16, 17, 18]
   18  [17, 18, 19]      [17, 19]  [17, 18, 19]
   19      [18, 19]          [18]      [18, 19]
2  0                       [0, 1]           [1]        [0, 1]
   1                    [0, 1, 2]        [0, 2]     [0, 1, 2]
   2                    [1, 2, 3]        [1, 3]     [1, 2, 3]
   3                    [2, 3, 4]        [2, 4]     [2, 3, 4]
   4                    [3, 4, 5]        [3, 5]     [3, 4, 5]
   5                    [4, 5, 6]        [4, 6]     [4, 5, 6]
   6                    [5, 6, 7]        [5, 7]     [5, 6, 7]
   7                    [6, 7, 8]        [6, 8]     [6, 7, 8]
   8                    [7, 8, 9]        [7, 9]     [7, 8, 9]
   9                   [8, 9, 10]       [8, 10]    [8, 9, 10]
   10                 [9, 10, 11]       [9, 11]   [9, 10, 11]
   11                [10, 11, 12]      [10, 12]  [10, 11, 12]
   12                [11, 12, 13]      [11, 13]  [11, 12, 13]
   13                [12, 13, 14]      [12, 14]  [12, 13, 14]
   14                [13, 14, 15]      [13, 15]  [13, 14, 15]
   15                [14, 15, 16]      [14, 16]  [14, 15, 16]
   16                [15, 16, 17]      [15, 17]  [15, 16, 17]
   17                [16, 17, 18]      [16, 18]  [16, 17, 18]
   18                [17, 18, 19]      [17, 19]  [17, 18, 19]
   19                    [18, 19]          [18]      [18, 19]
3  0                                     [0, 1]           [1]        [0, 1]
   1                                  [0, 1, 2]        [0, 2]     [0, 1, 2]
   2                                  [1, 2, 3]        [1, 3]     [1, 2, 3]
   3                                  [2, 3, 4]        [2, 4]     [2, 3, 4]
   4                                  [3, 4, 5]        [3, 5]     [3, 4, 5]
   5                                  [4, 5, 6]        [4, 6]     [4, 5, 6]
   6                                  [5, 6, 7]        [5, 7]     [5, 6, 7]
   7                                  [6, 7, 8]        [6, 8]     [6, 7, 8]
   8                                  [7, 8, 9]        [7, 9]     [7, 8, 9]
   9                                 [8, 9, 10]       [8, 10]    [8, 9, 10]
   10                               [9, 10, 11]       [9, 11]   [9, 10, 11]
   11                              [10, 11, 12]      [10, 12]  [10, 11, 12]
   12                              [11, 12, 13]      [11, 13]  [11, 12, 13]
   13                              [12, 13, 14]      [12, 14]  [12, 13, 14]
   14                              [13, 14, 15]      [13, 15]  [13, 14, 15]
   15                              [14, 15, 16]      [14, 16]  [14, 15, 16]
   16                              [15, 16, 17]      [15, 17]  [15, 16, 17]
   17                              [16, 17, 18]      [16, 18]  [16, 17, 18]
   18                              [17, 18, 19]      [17, 19]  [17, 18, 19]
   19                                  [18, 19]          [18]      [18, 19]
4  0                                                   [0, 1]           [1]
   1                                                [0, 1, 2]        [0, 2]
   2                                                [1, 2, 3]        [1, 3]
   3                                                [2, 3, 4]        [2, 4]
   4                                                [3, 4, 5]        [3, 5]
   5                                                [4, 5, 6]        [4, 6]
   6                                                [5, 6, 7]        [5, 7]
   7                                                [6, 7, 8]        [6, 8]
   8                                                [7, 8, 9]        [7, 9]
   9                                               [8, 9, 10]       [8, 10]
   10                                             [9, 10, 11]       [9, 11]
   11                                            [10, 11, 12]      [10, 12]
   12                                            [11, 12, 13]      [11, 13]
   13                                            [12, 13, 14]      [12, 14]
   14                                            [13, 14, 15]      [13, 15]
   15                                            [14, 15, 16]      [14, 16]
   16                                            [15, 16, 17]      [15, 17]
   17                                            [16, 17, 18]      [16, 18]
   18                                            [17, 18, 19]      [17, 19]
   19                                                [18, 19]          [18]
5  0                                                                 [0, 1]
   1                                                              [0, 1, 2]
   2                                                              [1, 2, 3]
   3                                                              [2, 3, 4]
   4                                                              [3, 4, 5]
   5                                                              [4, 5, 6]
   6                                                              [5, 6, 7]
   7                                                              [6, 7, 8]
   8                                                              [7, 8, 9]
   9                                                             [8, 9, 10]
   10                                                           [9, 10, 11]
   11                                                          [10, 11, 12]
   12                                                          [11, 12, 13]
   13                                                          [12, 13, 14]
   14                                                          [13, 14, 15]
   15                                                          [14, 15, 16]
   16                                                          [15, 16, 17]
   17                                                          [16, 17, 18]
   18                                                          [17, 18, 19]
   19                                                              [18, 19]
6  0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
7  0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
8  0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
9  0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
10 0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
11 0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
12 0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
13 0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
14 0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
15 0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
16 0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
17 0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
18 0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
19 0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19

                 5             6             7             8             9   \
0  0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
1  0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
2  0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
3  0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
4  0         [0, 1]
   1      [0, 1, 2]
   2      [1, 2, 3]
   3      [2, 3, 4]
   4      [3, 4, 5]
   5      [4, 5, 6]
   6      [5, 6, 7]
   7      [6, 7, 8]
   8      [7, 8, 9]
   9     [8, 9, 10]
   10   [9, 10, 11]
   11  [10, 11, 12]
   12  [11, 12, 13]
   13  [12, 13, 14]
   14  [13, 14, 15]
   15  [14, 15, 16]
   16  [15, 16, 17]
   17  [16, 17, 18]
   18  [17, 18, 19]
   19      [18, 19]
5  0            [1]        [0, 1]
   1         [0, 2]     [0, 1, 2]
   2         [1, 3]     [1, 2, 3]
   3         [2, 4]     [2, 3, 4]
   4         [3, 5]     [3, 4, 5]
   5         [4, 6]     [4, 5, 6]
   6         [5, 7]     [5, 6, 7]
   7         [6, 8]     [6, 7, 8]
   8         [7, 9]     [7, 8, 9]
   9        [8, 10]    [8, 9, 10]
   10       [9, 11]   [9, 10, 11]
   11      [10, 12]  [10, 11, 12]
   12      [11, 13]  [11, 12, 13]
   13      [12, 14]  [12, 13, 14]
   14      [13, 15]  [13, 14, 15]
   15      [14, 16]  [14, 15, 16]
   16      [15, 17]  [15, 16, 17]
   17      [16, 18]  [16, 17, 18]
   18      [17, 19]  [17, 18, 19]
   19          [18]      [18, 19]
6  0         [0, 1]           [1]        [0, 1]
   1      [0, 1, 2]        [0, 2]     [0, 1, 2]
   2      [1, 2, 3]        [1, 3]     [1, 2, 3]
   3      [2, 3, 4]        [2, 4]     [2, 3, 4]
   4      [3, 4, 5]        [3, 5]     [3, 4, 5]
   5      [4, 5, 6]        [4, 6]     [4, 5, 6]
   6      [5, 6, 7]        [5, 7]     [5, 6, 7]
   7      [6, 7, 8]        [6, 8]     [6, 7, 8]
   8      [7, 8, 9]        [7, 9]     [7, 8, 9]
   9     [8, 9, 10]       [8, 10]    [8, 9, 10]
   10   [9, 10, 11]       [9, 11]   [9, 10, 11]
   11  [10, 11, 12]      [10, 12]  [10, 11, 12]
   12  [11, 12, 13]      [11, 13]  [11, 12, 13]
   13  [12, 13, 14]      [12, 14]  [12, 13, 14]
   14  [13, 14, 15]      [13, 15]  [13, 14, 15]
   15  [14, 15, 16]      [14, 16]  [14, 15, 16]
   16  [15, 16, 17]      [15, 17]  [15, 16, 17]
   17  [16, 17, 18]      [16, 18]  [16, 17, 18]
   18  [17, 18, 19]      [17, 19]  [17, 18, 19]
   19      [18, 19]          [18]      [18, 19]
7  0                       [0, 1]           [1]        [0, 1]
   1                    [0, 1, 2]        [0, 2]     [0, 1, 2]
   2                    [1, 2, 3]        [1, 3]     [1, 2, 3]
   3                    [2, 3, 4]        [2, 4]     [2, 3, 4]
   4                    [3, 4, 5]        [3, 5]     [3, 4, 5]
   5                    [4, 5, 6]        [4, 6]     [4, 5, 6]
   6                    [5, 6, 7]        [5, 7]     [5, 6, 7]
   7                    [6, 7, 8]        [6, 8]     [6, 7, 8]
   8                    [7, 8, 9]        [7, 9]     [7, 8, 9]
   9                   [8, 9, 10]       [8, 10]    [8, 9, 10]
   10                 [9, 10, 11]       [9, 11]   [9, 10, 11]
   11                [10, 11, 12]      [10, 12]  [10, 11, 12]
   12                [11, 12, 13]      [11, 13]  [11, 12, 13]
   13                [12, 13, 14]      [12, 14]  [12, 13, 14]
   14                [13, 14, 15]      [13, 15]  [13, 14, 15]
   15                [14, 15, 16]      [14, 16]  [14, 15, 16]
   16                [15, 16, 17]      [15, 17]  [15, 16, 17]
   17                [16, 17, 18]      [16, 18]  [16, 17, 18]
   18                [17, 18, 19]      [17, 19]  [17, 18, 19]
   19                    [18, 19]          [18]      [18, 19]
8  0                                     [0, 1]           [1]        [0, 1]
   1                                  [0, 1, 2]        [0, 2]     [0, 1, 2]
   2                                  [1, 2, 3]        [1, 3]     [1, 2, 3]
   3                                  [2, 3, 4]        [2, 4]     [2, 3, 4]
   4                                  [3, 4, 5]        [3, 5]     [3, 4, 5]
   5                                  [4, 5, 6]        [4, 6]     [4, 5, 6]
   6                                  [5, 6, 7]        [5, 7]     [5, 6, 7]
   7                                  [6, 7, 8]        [6, 8]     [6, 7, 8]
   8                                  [7, 8, 9]        [7, 9]     [7, 8, 9]
   9                                 [8, 9, 10]       [8, 10]    [8, 9, 10]
   10                               [9, 10, 11]       [9, 11]   [9, 10, 11]
   11                              [10, 11, 12]      [10, 12]  [10, 11, 12]
   12                              [11, 12, 13]      [11, 13]  [11, 12, 13]
   13                              [12, 13, 14]      [12, 14]  [12, 13, 14]
   14                              [13, 14, 15]      [13, 15]  [13, 14, 15]
   15                              [14, 15, 16]      [14, 16]  [14, 15, 16]
   16                              [15, 16, 17]      [15, 17]  [15, 16, 17]
   17                              [16, 17, 18]      [16, 18]  [16, 17, 18]
   18                              [17, 18, 19]      [17, 19]  [17, 18, 19]
   19                                  [18, 19]          [18]      [18, 19]
9  0                                                   [0, 1]           [1]
   1                                                [0, 1, 2]        [0, 2]
   2                                                [1, 2, 3]        [1, 3]
   3                                                [2, 3, 4]        [2, 4]
   4                                                [3, 4, 5]        [3, 5]
   5                                                [4, 5, 6]        [4, 6]
   6                                                [5, 6, 7]        [5, 7]
   7                                                [6, 7, 8]        [6, 8]
   8                                                [7, 8, 9]        [7, 9]
   9                                               [8, 9, 10]       [8, 10]
   10                                             [9, 10, 11]       [9, 11]
   11                                            [10, 11, 12]      [10, 12]
   12                                            [11, 12, 13]      [11, 13]
   13                                            [12, 13, 14]      [12, 14]
   14                                            [13, 14, 15]      [13, 15]
   15                                            [14, 15, 16]      [14, 16]
   16                                            [15, 16, 17]      [15, 17]
   17                                            [16, 17, 18]      [16, 18]
   18                                            [17, 18, 19]      [17, 19]
   19                                                [18, 19]          [18]
10 0                                                                 [0, 1]
   1                                                              [0, 1, 2]
   2                                                              [1, 2, 3]
   3                                                              [2, 3, 4]
   4                                                              [3, 4, 5]
   5                                                              [4, 5, 6]
   6                                                              [5, 6, 7]
   7                                                              [6, 7, 8]
   8                                                              [7, 8, 9]
   9                                                             [8, 9, 10]
   10                                                           [9, 10, 11]
   11                                                          [10, 11, 12]
   12                                                          [11, 12, 13]
   13                                                          [12, 13, 14]
   14                                                          [13, 14, 15]
   15                                                          [14, 15, 16]
   16                                                          [15, 16, 17]
   17                                                          [16, 17, 18]
   18                                                          [17, 18, 19]
   19                                                              [18, 19]
11 0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
12 0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
13 0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
14 0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
15 0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
16 0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
17 0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
18 0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
19 0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19

                 10            11            12            13            14  \
0  0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
1  0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
2  0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
3  0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
4  0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
5  0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
6  0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
7  0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
8  0
   1
   2
   3
   4
   5
   6
   7
   8
   9
   10
   11
   12
   13
   14
   15
   16
   17
   18
   19
9  0         [0, 1]
   1      [0, 1, 2]
   2      [1, 2, 3]
   3      [2, 3, 4]
   4      [3, 4, 5]
   5      [4, 5, 6]
   6      [5, 6, 7]
   7      [6, 7, 8]
   8      [7, 8, 9]
   9     [8, 9, 10]
   10   [9, 10, 11]
   11  [10, 11, 12]
   12  [11, 12, 13]
   13  [12, 13, 14]
   14  [13, 14, 15]
   15  [14, 15, 16]
   16  [15, 16, 17]
   17  [16, 17, 18]
   18  [17, 18, 19]
   19      [18, 19]
10 0            [1]        [0, 1]
   1         [0, 2]     [0, 1, 2]
   2         [1, 3]     [1, 2, 3]

In [257]:
df

    0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [229]:
#not done yet
seen=set()
def make_move(x0,y0,x1,y1):
    #x0,y0 origianl coordinates
    #dest coords
    seen.add((x0,y0))
    seen.add((x1,y1))
    return seen

In [230]:
make_move(0,0,0,1)

{(0, 0), (0, 1)}

In [233]:
Range_df.ix[0,0]=""

In [235]:
Range_df.ix[0,1]=""

In [237]:
Range_df.ix[1,1]=""

In [239]:
Range_df.ix[1,0]=""

In [241]:
Range_df.ix[2,0]=""

In [243]:
Range_df.ix[2,1]=""

In [244]:
Range_df

             0          1          2          3
0 0
  1
  2     [1, 3]  [1, 2, 3]
  3        [2]     [2, 3]
1 0
  1
  2  [1, 2, 3]     [1, 3]  [1, 2, 3]
  3     [2, 3]        [2]     [2, 3]
2 0
  1
  2             [1, 2, 3]     [1, 3]  [1, 2, 3]
  3                [2, 3]        [2]     [2, 3]
3 0                           [0, 1]        [1]
  1                        [0, 1, 2]     [0, 2]
  2                        [1, 2, 3]     [1, 3]
  3                           [2, 3]        [2]

In [245]:
Range_df.ix[2,2]=""

In [246]:
Range_df

             0          1          2       3
0 0
  1
  2     [1, 3]  [1, 2, 3]
  3        [2]     [2, 3]
1 0
  1
  2  [1, 2, 3]     [1, 3]  [1, 2, 3]
  3     [2, 3]        [2]     [2, 3]
2 0
  1
  2
  3                [2, 3]        [2]  [2, 3]
3 0                           [0, 1]     [1]
  1                        [0, 1, 2]  [0, 2]
  2                        [1, 2, 3]  [1, 3]
  3                           [2, 3]     [2]